global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'ai_callcenter'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics